### ISSUE TITLE
STR, DEX and WIL need current/max scores

### ISSUE THREAD

**Issue by ScottMaclure** [voidcase/IntoTheOdd-FoundryVTT#19]
Ability score damage is a key mechanic of ItO. The current character sheet has only 1 value. Suggest refactoring the sheet to have current/max ability scores, similar to HP.

**Comment by voidcase** [comment]
You're totally right! When I put together this module I had a misunderstanding about the rules. I somehow missed the "long rest" section and thus thought that ability score damage was _permanent_ and that the only way your ability scores could increase was through the experience levels system. I liked the idea of this so much that I didn't realize it wasn't true.

I don't think it will be a super big operation to fix it. This module needs an update anyway since ItO remastered is on its way.

**Comment by ScottMaclure** [comment]
Thanks for reviewing/merging... next step is releasing/tagging?

https://github.com/voidcase/IntoTheOdd-FoundryVTT/tags

**Comment by voidcase** [comment]
@ScottMaclure Sorry that it took a while but now v1.3.0 is released with your fix :)
