### ISSUE TITLE
Foundry VTT v10 Support

### ISSUE THREAD

**Issue by bluefroguk1** [voidcase/IntoTheOdd-FoundryVTT#27]
Are there any plans to update to v10?

**Comment by adamglinder** [comment]
Firstly, thank you for creating this game system! Very much appreciated :-)

I've found a problem in that the latest version 1.3.0 points to 1.2.0, so whenever I try to update it stays on 1.2.0

With help I've found a work around and successfully installed 1.3 on Forge, but it'd be good to have this corrected especially with the Remastered version of Into the Odd recently released.

**Comment by voidcase** [comment]
Hi!

I have not given up on this project but development has definitely slowed since I no longer use it myself. I recently started trying to update to v10, but I am having trouble getting rid of some of the warnings (for things that will soon be deprecated). It technically still works though, so I could make a release pretty soon and fix the version problem.

Updating to include the new features in ItO remastered will be done separately, and will require some more time.

**Comment by adamglinder** [comment]
Cool, good to know - it works perfectly in v10 Foundry for me, and again I
appreciate you creating this system!
When I queried it with the Forge's admin they thought it needed to have the
system manifest point to the zip file of 1.3.0, as it seems to be currently
pointing to 1.2.0 zip.


 Adam Linder
 T: +27 062 117 6739

**Comment by voidcase** [comment]
I released v1.3.1 just now which only fixes the problem that @adamglinder found (thanks <3)
It doesn't include my recent attempt to become warning-free in v10, but it makes it playable again.

**Comment by Qaw** [comment]
v10 compatibility done
